// サブスクサービス追加用
export const ADD_SUBSCRIPTIOM_CARD_START = "ADD_SUBSCRIPTIOM_CARD_START";
export const ADD_SUBSCRIPTIOM_CARD_SUCCESS = "ADD_SUBSCRIPTIOM_CARD_SUCCESS";
export const ADD_SUBSCRIPTIOM_CARD_FAILURE = "ADD_SUBSCRIPTIOM_CARD_FAILURE";

// サブスクサービス編集用
export const EDIT_SUBSCRIPTIOM_CARD_START = "EDIT_SUBSCRIPTIOM_CARD_START";
export const EDIT_SUBSCRIPTIOM_CARD_SUCCESS = "EDIT_SUBSCRIPTIOM_CARD_SUCCESS";
export const EDIT_SUBSCRIPTIOM_CARD_FAILURE = "EDIT_SUBSCRIPTIOM_CARD_FAILURE";

// サブスクサービス取得用
export const GET_ALL_SUBSCRIPTIOM_CARD_START = "GET_ALL_SUBSCRIPTIOM_CARD_START";
export const GET_ALL_SUBSCRIPTIOM_CARD_SUCCESS = "GET_ALL_SUBSCRIPTIOM_CARD_SUCCESS";
export const GET_ALL_SUBSCRIPTIOM_CARD_FAILURE = "GET_ALL_SUBSCRIPTIOM_CARD_FAILURE";

// サブスクサービス削除用
export const DELETE_SUBSCRIPTIOM_CARD_START = "DELETE_SUBSCRIPTIOM_CARD_START";
export const DELETE_SUBSCRIPTIOM_CARD_SUCCESS = "DELETE_SUBSCRIPTIOM_CARD_SUCCESS";
export const DELETE_SUBSCRIPTIOM_CARD_FAILURE = "DELETE_SUBSCRIPTIOM_CARD_FAILURE";

// ログイン用
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// ログイン状態監視用
export const LOGIN_STATUS_MONITORING_START = "LOGIN_STATUS_MONITORING_START";
export const LOGIN_STATUS_MONITORING_SUCCESS = "LOGIN_STATUS_MONITORING_SUCCESS";
export const LOGIN_STATUS_MONITORING_FAILURE = "LOGIN_STATUS_MONITORING_FAILURE";

// ログアウト用
export const LOGOUT_START = "LOGOUT_START";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// 合計金額計算用
export const AMOUNT_CALCULATION_START = "AMOUNT_CALCULATION_START";
export const AMOUNT_CALCULATION_SUCCESS = "AMOUNT_CALCULATION_SUCCESS";
export const AMOUNT_CALCULATION_FAILURE = "AMOUNT_CALCULATION_FAILURE";

// 合計金額取得用
export const GET_AMOUNT_START = "GET_AMOUNT_START";
export const GET_AMOUNT_SUCCESS = "GET_AMOUNT_SUCCESS";
export const GET_AMOUNT_FAILURE = "GET_AMOUNT_FAILURE";