// サブスクサービス追加用
export const ADD_SUBSCRIPTIOM_CARD_START = "ADD_SUBSCRIPTIOM_CARD_START";
export const ADD_SUBSCRIPTIOM_CARD_SUCCESS = "ADD_SUBSCRIPTIOM_CARD_SUCCESS";
export const ADD_SUBSCRIPTIOM_CARD_FAILURE = "ADD_SUBSCRIPTIOM_CARD_FAILURE";

// サブスクサービス編集用
export const EDIT_SUBSCRIPTIOM_CARD_START = "EDIT_SUBSCRIPTIOM_CARD_START";
export const EDIT_SUBSCRIPTIOM_CARD_SUCCESS = "EDIT_SUBSCRIPTIOM_CARD_SUCCESS";
export const EDIT_SUBSCRIPTIOM_CARD_FAILURE = "EDIT_SUBSCRIPTIOM_CARD_FAILURE";

// サブスクサービス取得用
export const GET_ALL_SUBSCRIPTIOM_CARD_START = "GET_ALL_SUBSCRIPTIOM_CARD_START";
export const GET_ALL_SUBSCRIPTIOM_CARD_SUCCESS = "GET_ALL_SUBSCRIPTIOM_CARD_SUCCESS";
export const GET_ALL_SUBSCRIPTIOM_CARD_FAILURE = "GET_ALL_SUBSCRIPTIOM_CARD_FAILURE";

// サブスクサービス削除用
export const DELETE_SUBSCRIPTIOM_CARD_START = "DELETE_SUBSCRIPTIOM_CARD_START";
export const DELETE_SUBSCRIPTIOM_CARD_SUCCESS = "DELETE_SUBSCRIPTIOM_CARD_SUCCESS";
export const DELETE_SUBSCRIPTIOM_CARD_FAILURE = "DELETE_SUBSCRIPTIOM_CARD_FAILURE";