export const ADD_SUBSCRIPTIOM_CARD_START = "ADD_SUBSCRIPTIOM_CARD_START";
export const ADD_SUBSCRIPTIOM_CARD_SUCCESS = "ADD_SUBSCRIPTIOM_CARD_SUCCESS";
export const ADD_SUBSCRIPTIOM_CAR_FAILURE = "ADD_SUBSCRIPTIOM_CAR_FAILURE";
